<%@ Page Title="" Language="C#" MasterPageFile="~/Fitness.Master" AutoEventWireup="true" CodeFile="PostPurchaseForm.aspx.cs" Inherits="Pages_PostPurchase_PostPurchaseForm" %>

<asp:Content ID="Content1" ContentPlaceHolderID="FitnessContent" runat="Server">

    <link href="../Meals/Meal.css" rel="stylesheet" />
    <link href="PostPurchaseForm.css" rel="stylesheet" />
    <div class="container-fluid containerBg">
        <div class="mealContainer">
            <asp:Label runat="server" CssClass="lblMealHead  lblHead blink">Your Diet and WorkOut Plan Will Be  Generated By Branch Admin</asp:Label>
        </div>
        <div id="divMealType" runat="server" visible="true">
            <%--<div class="divMealTypeNav">
                <asp:LinkButton ID="lnkBreakFast" runat="server" class="lblMealTypeHead lblMealTypeHeadSelect">Recommanded</asp:LinkButton>

            </div>--%>
            <div class="row">
                <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3">

                    <div id="DivBreakFast" class="Mealtype" runat="server">
                        <div class="row">
                            <div class="col-8 col-sm-8 col-md-8 col-lg-8 col-xl-8 mb-3">
                                <div class="row">
                                    <div class="col-12 col-sm-4 col-md-4 col-lg-4 col-xl-4 DivBreakFast">

                                        <iframe class="VideoWork" src="https://www.youtube.com/embed/M0uO8X3_tEA" title="YouTube video player" frameborder="0"
                                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                                        <br />
                                        <label class="lblMealName">HIIT</label>

                                    </div>
                                    <div class="col-12 col-sm-4 col-md-4 col-lg-4 col-xl-4 DivBreakFast">

                                        <iframe class="VideoWork" src="https://www.youtube.com/embed/HRkNfdlm5Qs" title="YouTube video player" frameborder="0"
                                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                                        <br />
                                        <label class="lblMealName">Zumba</label>

                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 DivNewClass">
                                        <asp:Label ID="NewClasses" runat="server" CssClass="NewClass">New Classes</asp:Label>
                                        <div class="row">
                                            <div class="col-12 col-sm-3 col-md-3 col-lg-3 col-xl-3 DivClass">

                                                <asp:ImageButton runat="server" CssClass="imgMeal" ImageUrl="~/Images/DietWotkOut/1.png" /><br />

                                            </div>
                                            <div class="col-12 col-sm-3 col-md-3 col-lg-3 col-xl-3 DivClass">

                                                <asp:ImageButton runat="server" CssClass="imgMeal" ImageUrl="~/Images/DietWotkOut/2.png" /><br />

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-3 col-sm-3 col-md-3 col-lg-3 col-xl-3 mb-3 DivActivity">
                                <asp:Label ID="WeeklyProgress" runat="server" CssClass="weekly-header" Text="Weekly Progress">
                                    <span>Weekly Progress</span>
                                </asp:Label>
                                <div class="icon-sec">
                                    <img src="../../Images/DietWotkOut/icon-weekly-goal.b61c80cd.svg" />
                                </div>
                                <asp:Label ID="work" runat="server" CssClass="itemsName">0/2</asp:Label>
                                 <br />
                                <asp:Label ID="lbl2" runat="server" CssClass="item-subname">WorkOuts</asp:Label>
                             <hr class="hrd" />

                                 <div class="icon-sec">
                                    <img src="../../Images/DietWotkOut/icon-cal-fire.9f062770.svg" />
                                </div>
                                <asp:Label ID="Label1" runat="server" CssClass="itemsName">0</asp:Label>
                                <br />
                                <asp:Label ID="Label2" runat="server" CssClass="item-subname">Calories</asp:Label>
                                 <hr  class="hrd" />

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
</asp:Content>

